# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load netblock data into a table. Returns a pointer to the table.
#'
#' @export
nbBuildNetblockTable <- function(BaseAndMask, IPaddrStrings, Mask, Description) {
    .Call('_netblockr_nbBuildNetblockTable', PACKAGE = 'netblockr', BaseAndMask, IPaddrStrings, Mask, Description)
}

#' Add the unique netmasks to the table in the desired search order, usually largest netmask first to find shortest match
#'
#' @export
nbSetMaskOrder <- function(nbt, Masks) {
    invisible(.Call('_netblockr_nbSetMaskOrder', PACKAGE = 'netblockr', nbt, Masks))
}

#' Dumps netblock data table into a data frame
#'
#' @export
nbGetNetblockTable <- function(nbt) {
    .Call('_netblockr_nbGetNetblockTable', PACKAGE = 'netblockr', nbt)
}

#' Lookup IPv4 address in a netblock table
#'
#' @export
nbLookupIPaddrs <- function(nbt, IPaddrStrings) {
    .Call('_netblockr_nbLookupIPaddrs', PACKAGE = 'netblockr', nbt, IPaddrStrings)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_netblockr_RcppExport_registerCCallable', PACKAGE = 'netblockr')
})
